spring:
  activemq:
    broker-url: failover:(auto+nio://192.168.174.133:61608,auto+nio://192.168.174.129:61608,auto+nio://192.168.174.132:61608)?randomize=false
    password: admin
    user: admin
  jms:
    pub-sub-domain: true
server:
  port: 8089

activemq:
  queue: spring-boot-activemq-queue
  topic: spring-boot-activemq-topic

username: dailingfei
